server:
  port: ${PORT}
spring:
  application:
    name: workshare
  datasource:
    url: ${URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: always
  config:
    import: file:env.properties

logging:
  level:
    org:
      springframework:
        security: DEBUG