server:
  port: 9108
spring:
  application:
    name: workshare
  datasource:
    url: jdbc:mariadb://localhost:3306/workshare
    username: root
    password: 595978
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: always
  config:
    import: file:env.properties